/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManagerPanel;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class ManagerDashboardPanel extends GradientPanel {
    private final JPanel workarea;
    private final EcoSystem system;

    /**
     * Creates new form ManagerDashboardPanel
     */
    public ManagerDashboardPanel(JPanel workarea, UserAccount ua, EcoSystem system) {
         super(
            new Color[] {
                new Color(70, 130, 180),     // Steel Blue
                new Color(176, 196, 222),    // Light Steel Blue
                new Color(192, 192, 192)     // Silver
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system   = system;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManagerDashboard = new javax.swing.JLabel();
        btnDistributionAssignments = new javax.swing.JButton();
        btnTicketingRequests = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblManagerDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblManagerDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagerDashboard.setText("Manager Dashboard");

        btnDistributionAssignments.setText("Distribution Assignments");
        btnDistributionAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributionAssignmentsActionPerformed(evt);
            }
        });

        btnTicketingRequests.setText("Ticketing Requests");
        btnTicketingRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketingRequestsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManagerDashboard)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnDistributionAssignments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnTicketingRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblManagerDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDistributionAssignments, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(btnTicketingRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDistributionAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributionAssignmentsActionPerformed
        // TODO add your handling code here:
         ProcessDistributionAssignmentPanel p = 
           new ProcessDistributionAssignmentPanel(workarea, system);
        workarea.add("ProcDist", p);
        ((CardLayout)workarea.getLayout()).next(workarea);
    }//GEN-LAST:event_btnDistributionAssignmentsActionPerformed

    private void btnTicketingRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketingRequestsActionPerformed
        // TODO add your handling code here:
        TicketingRequestPanel t = new TicketingRequestPanel(workarea, system);
        workarea.add("TicketReq", t);
        ((CardLayout)workarea.getLayout()).next(workarea);
    
    }//GEN-LAST:event_btnTicketingRequestsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDistributionAssignments;
    private javax.swing.JButton btnTicketingRequests;
    private javax.swing.JLabel lblManagerDashboard;
    // End of variables declaration//GEN-END:variables
}
