/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManagerPanel;
import Business.EcoSystem;
import Business.Role.ConcessionStaffRole;
import Business.Role.TechnicianRole;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DistributionAssignmentRequest;
import Business.WorkRequest.StaffAssignmentRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class ProcessDistributionAssignmentPanel extends GradientPanel {
     private final JPanel workarea;
    private final EcoSystem system;

    /**
     * Creates new form ProcessDistributionAssignmentPanel
     */
    public ProcessDistributionAssignmentPanel(JPanel workarea, EcoSystem system) {
        super(
            new Color[] {
                new Color(70, 130, 180),     // Steel Blue
                new Color(176, 196, 222),    // Light Steel Blue
                new Color(192, 192, 192)     // Silver
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system   = system;
        initComponents();
        populateTable();
        populateStaffCombo();
        rebuildProcessDistributionAssignmentLayout();
    }
    
    public void rebuildProcessDistributionAssignmentLayout() {
    setLayout(new BorderLayout());

    JPanel topPanel = new JPanel(new BorderLayout());
    topPanel.setOpaque(false);
    topPanel.add(btnBack, BorderLayout.WEST);
    topPanel.add(lblProcessDistributionAssignments, BorderLayout.CENTER);

    JPanel centerPanel = new JPanel();
    centerPanel.setOpaque(false);
    centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));

    jScrollPane1.setAlignmentX(Component.CENTER_ALIGNMENT);
    centerPanel.add(Box.createVerticalStrut(30));
    centerPanel.add(jScrollPane1);
    centerPanel.add(Box.createVerticalStrut(30));

    JPanel assignPanel = new JPanel();
    assignPanel.setOpaque(false);
    assignPanel.add(lblPickStaff);
    assignPanel.add(cmbPickStaff);
    assignPanel.add(btnAssigntoStaff);
    assignPanel.setAlignmentX(Component.CENTER_ALIGNMENT);

    centerPanel.add(assignPanel);
    centerPanel.add(Box.createVerticalGlue());

    add(topPanel, BorderLayout.NORTH);
    add(centerPanel, BorderLayout.CENTER);
}
    
    private void populateTable() {
        DefaultTableModel m = (DefaultTableModel)tblProcessDistributionAssignments.getModel();
        m.setRowCount(0);
        for (DistributionAssignmentRequest r : system.getDistributionAssignments()) {
            m.addRow(new Object[]{
                r.getMovieTitle(),
                r.getBudget(),
                r.getStatus(),
                r.getAssignedManager()==null? "<unassigned>": r.getAssignedManager()
            });
        }
    }
    
    private void populateStaffCombo() {
        cmbPickStaff.removeAllItems();
        for (UserAccount ua : system.getUserAccountDirectory().getUserList()) {
            String role = ua.getRole().toString();
            if ( ua.getRole() instanceof TechnicianRole
          || ua.getRole() instanceof ConcessionStaffRole ) {
            cmbPickStaff.addItem(ua.getusername());
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcessDistributionAssignments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcessDistributionAssignments = new javax.swing.JTable();
        lblPickStaff = new javax.swing.JLabel();
        cmbPickStaff = new javax.swing.JComboBox<>();
        btnAssigntoStaff = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblProcessDistributionAssignments.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProcessDistributionAssignments.setText("Process Distribution Assignments");

        tblProcessDistributionAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Title", "Budget", "Status", "Assigned Staff"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProcessDistributionAssignments);
        if (tblProcessDistributionAssignments.getColumnModel().getColumnCount() > 0) {
            tblProcessDistributionAssignments.getColumnModel().getColumn(0).setResizable(false);
            tblProcessDistributionAssignments.getColumnModel().getColumn(1).setResizable(false);
            tblProcessDistributionAssignments.getColumnModel().getColumn(2).setResizable(false);
            tblProcessDistributionAssignments.getColumnModel().getColumn(3).setResizable(false);
        }

        lblPickStaff.setText("Pick Staff :");

        cmbPickStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPickStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPickStaffActionPerformed(evt);
            }
        });

        btnAssigntoStaff.setText("Assign to Staff");
        btnAssigntoStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssigntoStaffActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)
                        .addGap(30, 30, 30)
                        .addComponent(lblProcessDistributionAssignments))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblPickStaff)
                .addGap(33, 33, 33)
                .addComponent(cmbPickStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssigntoStaff)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcessDistributionAssignments)
                    .addComponent(btnBack))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPickStaff)
                    .addComponent(cmbPickStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssigntoStaff))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssigntoStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssigntoStaffActionPerformed
        // TODO add your handling code here:
        int row = tblProcessDistributionAssignments.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(this,"Select a row.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String staff = (String)cmbPickStaff.getSelectedItem();
        DistributionAssignmentRequest dar = system.getDistributionAssignments().get(row);
        dar.setAssignedManager(staff);
        system.addStaffAssignmentRequest(
          new StaffAssignmentRequest(dar.getMovieTitle(), dar.getBudget(), staff)
        );
        JOptionPane.showMessageDialog(this,"Assigned to "+staff,"Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();

    }//GEN-LAST:event_btnAssigntoStaffActionPerformed

    private void cmbPickStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPickStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPickStaffActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssigntoStaff;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbPickStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPickStaff;
    private javax.swing.JLabel lblProcessDistributionAssignments;
    private javax.swing.JTable tblProcessDistributionAssignments;
    // End of variables declaration//GEN-END:variables
}
