/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManagerPanel;
import Business.EcoSystem;
import Business.WorkRequest.TicketingRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ushakeshravya
 */
public class TicketingRequestPanel extends javax.swing.JPanel {
    private final JPanel workarea;
    private final EcoSystem system;


    /**
     * Creates new form TicketingRequestPanel
     */
    public TicketingRequestPanel(JPanel workarea, EcoSystem system) {
        this.workarea = workarea;
        this.system   = system;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewTicketingRequest = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblMovieTitle = new javax.swing.JLabel();
        txtMovieTitle = new javax.swing.JTextField();
        lblShowTime = new javax.swing.JLabel();
        txtShowTime = new javax.swing.JTextField();
        lblNumberofTickets = new javax.swing.JLabel();
        txtNumberofTickets = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblNewTicketingRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNewTicketingRequest.setText("New Ticketing Request");

        lblCustomerName.setText("Customer Name :");

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        lblMovieTitle.setText("Movie Title :    ");

        txtMovieTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieTitleActionPerformed(evt);
            }
        });

        lblShowTime.setText("Show Time :");

        txtShowTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowTimeActionPerformed(evt);
            }
        });

        lblNumberofTickets.setText("Number of Tickets :");

        txtNumberofTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberofTicketsActionPerformed(evt);
            }
        });

        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblCustomerName))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMovieTitle)
                                    .addComponent(lblShowTime)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNumberofTickets)
                                .addGap(15, 15, 15)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerName)
                            .addComponent(txtMovieTitle)
                            .addComponent(txtShowTime)
                            .addComponent(txtNumberofTickets, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNewTicketingRequest)))
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnSubmitRequest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNewTicketingRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovieTitle)
                    .addComponent(txtMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowTime)
                    .addComponent(txtShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberofTickets)
                    .addComponent(txtNumberofTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btnSubmitRequest)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtMovieTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieTitleActionPerformed

    private void txtNumberofTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberofTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberofTicketsActionPerformed

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
        String cust = txtCustomerName.getText().trim();
        String mov  = txtMovieTitle.getText().trim();
        String time = txtShowTime.getText().trim();
        String numS = txtNumberofTickets.getText().trim();
        if (cust.isEmpty()||mov.isEmpty()||time.isEmpty()||numS.isEmpty()) {
            JOptionPane.showMessageDialog(this,"All fields required.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int num;
        try { num = Integer.parseInt(numS); }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Tickets must be numeric.","Error",JOptionPane.ERROR_MESSAGE);
            return;
       
        }
        system.addTicketingRequest(new TicketingRequest(cust,mov ,time, num));
        JOptionPane.showMessageDialog(this,"Ticketing request submitted.","Success",JOptionPane.INFORMATION_MESSAGE);
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);


    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtShowTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblNewTicketingRequest;
    private javax.swing.JLabel lblNumberofTickets;
    private javax.swing.JLabel lblShowTime;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtMovieTitle;
    private javax.swing.JTextField txtNumberofTickets;
    private javax.swing.JTextField txtShowTime;
    // End of variables declaration//GEN-END:variables
}
