/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProducerPanel;

import Business.EcoSystem;
import Business.WorkRequest.MovieAcquisitionRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author ushakeshravya
 */
public class MovieAcquisitionRequestPanel extends javax.swing.JPanel {
    private final JPanel workarea;
     private final EcoSystem system; 


    /**
     * Creates new form MovieAcquisitionRequestPanel
     */
    public MovieAcquisitionRequestPanel(JPanel workarea, EcoSystem system) {
        this.workarea = workarea;
        this.system   = system;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblNewAcquisitionRequest = new javax.swing.JLabel();
        lblMovieTitle = new javax.swing.JLabel();
        txtMovieTitle = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblNewAcquisitionRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNewAcquisitionRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewAcquisitionRequest.setText("New Acquisition Request");

        lblMovieTitle.setText("Movie Title :");

        lblDescription.setText("Description:");

        lblBudget.setText("Budget :");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)
                        .addGap(103, 103, 103)
                        .addComponent(lblNewAcquisitionRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieTitle)
                            .addComponent(lblDescription)
                            .addComponent(lblBudget))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription)
                            .addComponent(txtMovieTitle)
                            .addComponent(txtBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnSubmit)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblNewAcquisitionRequest))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovieTitle)
                    .addComponent(txtMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBudget)
                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(btnSubmit)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         String title  = txtMovieTitle.getText().trim();
    String budget = txtBudget.getText().trim();
    if (title.isEmpty() || budget.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title and Budget are required.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double b;
    try { b = Double.parseDouble(budget); }
    catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Budget must be a number", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // add to system
    MovieAcquisitionRequest req = new MovieAcquisitionRequest(title, b);
    system.addMovieRequest(req);

    // go back and refresh the dashboard
    workarea.remove(this);
    CardLayout layout = (CardLayout)workarea.getLayout();
    layout.previous(workarea);

    Component[] comps = workarea.getComponents();
    Component last  = comps[comps.length-1];
    if (last instanceof ProducerDashboardPanel) {
        ((ProducerDashboardPanel)last).populateTable();
    }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblNewAcquisitionRequest;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtMovieTitle;
    // End of variables declaration//GEN-END:variables
}
