/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProducerPanel;

import Business.EcoSystem;
import Business.WorkRequest.MovieAcquisitionRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class MovieAcquisitionRequestPanel extends GradientPanel {
    private final JPanel workarea;
     private final EcoSystem system; 


    /**
     * Creates new form MovieAcquisitionRequestPanel
     */
    public MovieAcquisitionRequestPanel(JPanel workarea, EcoSystem system) {
         super(
            new Color[] {
                new Color(139, 0, 0),     // red
                new Color(30, 30, 30),    // black
                new Color(192, 192, 192)  // silver
            },
            new float[] { 0f, 0.5f, 1f }
        );
         
        this.workarea = workarea;
        this.system   = system;
        initComponents();
        rebuildAcquisitionFormLayout();

    }
    private void rebuildAcquisitionFormLayout() {
    this.removeAll();
    this.setLayout(new BorderLayout());
    this.setOpaque(false);

    // --- Top Bar ---
    JPanel topPanel = new JPanel(new BorderLayout());
    topPanel.setOpaque(false);
    topPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
    topPanel.add(btnBack, BorderLayout.WEST);

    lblNewAcquisitionRequest.setHorizontalAlignment(SwingConstants.CENTER);
    lblNewAcquisitionRequest.setFont(new Font("SansSerif", Font.BOLD, 20));
    topPanel.add(lblNewAcquisitionRequest, BorderLayout.CENTER);
    this.add(topPanel, BorderLayout.NORTH);

    // --- Center Form ---
    JPanel formPanel = new JPanel();
    formPanel.setOpaque(false);
    formPanel.setLayout(new BoxLayout(formPanel, BoxLayout.Y_AXIS));
    formPanel.setBorder(BorderFactory.createEmptyBorder(40, 80, 40, 80));

    addFormRow(formPanel, lblMovieTitle, txtMovieTitle);
    addFormRow(formPanel, lblDescription, txtDescription);
    addFormRow(formPanel, lblBudget, txtBudget);

    btnSubmit.setAlignmentX(Component.CENTER_ALIGNMENT);
    formPanel.add(Box.createVerticalStrut(30));
    formPanel.add(btnSubmit);

    this.add(formPanel, BorderLayout.CENTER);

    this.revalidate();
    this.repaint();
}

private void addFormRow(JPanel panel, JLabel label, JTextField field) {
    JPanel row = new JPanel();
    row.setOpaque(false);
    row.setLayout(new BoxLayout(row, BoxLayout.X_AXIS));
    label.setPreferredSize(new Dimension(100, 25));
    row.add(label);
    row.add(Box.createHorizontalStrut(10));
    row.add(field);
    row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 35));
    panel.add(row);
    panel.add(Box.createVerticalStrut(20));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblNewAcquisitionRequest = new javax.swing.JLabel();
        lblMovieTitle = new javax.swing.JLabel();
        txtMovieTitle = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblNewAcquisitionRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNewAcquisitionRequest.setForeground(new java.awt.Color(255, 255, 255));
        lblNewAcquisitionRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewAcquisitionRequest.setText("New Acquisition Request");

        lblMovieTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle.setText("Movie Title :");

        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Description:");

        lblBudget.setForeground(new java.awt.Color(255, 255, 255));
        lblBudget.setText("Budget :");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieTitle)
                            .addComponent(lblDescription)
                            .addComponent(lblBudget))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription)
                            .addComponent(txtMovieTitle)
                            .addComponent(txtBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnSubmit)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(lblNewAcquisitionRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewAcquisitionRequest)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovieTitle)
                    .addComponent(txtMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBudget)
                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(btnSubmit)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         String title  = txtMovieTitle.getText().trim();
    String budget = txtBudget.getText().trim();
    if (title.isEmpty() || budget.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title and Budget are required.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double b;
    try { b = Double.parseDouble(budget); }
    catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Budget must be a number", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // add to system
    MovieAcquisitionRequest req = new MovieAcquisitionRequest(title, b);
    system.addMovieRequest(req);

    // go back and refresh the dashboard
    workarea.remove(this);
    CardLayout layout = (CardLayout)workarea.getLayout();
    layout.previous(workarea);

    Component[] comps = workarea.getComponents();
    Component last  = comps[comps.length-1];
    if (last instanceof ProducerDashboardPanel) {
        ((ProducerDashboardPanel)last).populateTable();
    }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblNewAcquisitionRequest;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtMovieTitle;
    // End of variables declaration//GEN-END:variables
}
