/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProducerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.MovieAcquisitionRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.GradientPanel;


/**
 *
 * @author ushakeshravya
 */
public class ProducerDashboardPanel extends ui.GradientPanel {
    private final JPanel workarea ;
    private final EcoSystem system ;


    /**
     * Creates new form ProducerWorkAreaPanel
     */
    public ProducerDashboardPanel(JPanel workarea, UserAccount account, EcoSystem system) {
         super(
        new Color[] {
            new Color(139, 0, 0),     // red
            new Color(30, 30, 30),    // black
            new Color(192, 192, 192)  // silver
        },
        new float[] { 0f, 0.5f, 1f }
    );
         
         // ✅ Then initialize your variables
        this.workarea = workarea;
        this.system = system;
        
        initComponents();
        populateTable();
        
    }
    
    public void populateTable() {
    DefaultTableModel model = (DefaultTableModel)tblProducerDashboard.getModel();
    model.setRowCount(0);
    for (MovieAcquisitionRequest r : system.getMovieRequests()) {
        model.addRow(new Object[]{ r.getMovieTitle(), r.getBudget(), r.getStatus() });
    }


}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProducerDashboard = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducerDashboard = new javax.swing.JTable();
        btnNewAquisitionRequest = new javax.swing.JButton();

        lblProducerDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProducerDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducerDashboard.setText("Producer Dashboard");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblProducerDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Title", "Budget", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducerDashboard);
        if (tblProducerDashboard.getColumnModel().getColumnCount() > 0) {
            tblProducerDashboard.getColumnModel().getColumn(0).setResizable(false);
            tblProducerDashboard.getColumnModel().getColumn(1).setResizable(false);
            tblProducerDashboard.getColumnModel().getColumn(2).setResizable(false);
        }

        btnNewAquisitionRequest.setText("New Aquisition Request");
        btnNewAquisitionRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAquisitionRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(lblProducerDashboard)
                .addGap(187, 187, 187))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnNewAquisitionRequest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducerDashboard)
                    .addComponent(btnBack))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnNewAquisitionRequest)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNewAquisitionRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAquisitionRequestActionPerformed
        // TODO add your handling code here:
          // 1) Instantiate your request panel
       MovieAcquisitionRequestPanel reqPanel = 
        new MovieAcquisitionRequestPanel(workarea, system);   // ← pass system
    workarea.add("MovieAcqReqPanel", reqPanel);
    ((CardLayout) workarea.getLayout()).next(workarea);
    }//GEN-LAST:event_btnNewAquisitionRequestActionPerformed

public void addAcquisitionRequestRow(String title, String budget, String status) {
    DefaultTableModel model = (DefaultTableModel) tblProducerDashboard.getModel();
    model.addRow(new Object[]{ title, budget, status });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewAquisitionRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProducerDashboard;
    private javax.swing.JTable tblProducerDashboard;
    // End of variables declaration//GEN-END:variables
}
