/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.MainFrame;


import Business.EcoSystem;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;


/**
 *
 * @author ushakeshravya
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MsinFrame
     */
    public MainFrame() {
   
initComponents();
  ImageBackgroundPanel bgPanel = new ImageBackgroundPanel("/images/cinmaGif.gif");
    bgPanel.setLayout(new CardLayout());                // ✅ Add CardLayout
    this.workarea = bgPanel;                            // ✅ update reference so login works
    jSplitPane1.setRightComponent(workarea);            // ✅ now uses bgPanel

    // style the label (assumes it is defined in .form and added already)
    lblCinemaAndTheatreManagementSystem.setFont(new Font("Times New Roman", Font.BOLD, 40));
    lblCinemaAndTheatreManagementSystem.setForeground(Color.YELLOW); // adjust if needed
       lblCinemaAndTheatreManagementSystem.setBounds(0, 20, workarea.getWidth(), 50); // full width
    lblCinemaAndTheatreManagementSystem.setHorizontalAlignment(SwingConstants.CENTER);
    lblCinemaAndTheatreManagementSystem.setOpaque(false); // Transparent background

    workarea.add(lblCinemaAndTheatreManagementSystem);
    workarea.setComponentZOrder(lblCinemaAndTheatreManagementSystem, 0); 
    }
    
 
    
    private EcoSystem system = new EcoSystem(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        login = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogic = new javax.swing.JButton();
        workarea = new javax.swing.JPanel();
        lblCinemaAndTheatreManagementSystem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsername.setText("Username : ");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblPassword.setText("Password :");

        btnLogic.setText("Login");
        btnLogic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsername))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblPassword)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnLogic)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnLogic)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(login);

        workarea.setLayout(new java.awt.CardLayout());

        lblCinemaAndTheatreManagementSystem.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblCinemaAndTheatreManagementSystem.setForeground(new java.awt.Color(204, 204, 0));
        lblCinemaAndTheatreManagementSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinemaAndTheatreManagementSystem.setText("Cinema And Theatre Management System");
        workarea.add(lblCinemaAndTheatreManagementSystem, "card2");

        jSplitPane1.setRightComponent(workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLogicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogicActionPerformed
        // TODO add your handling code here:
        System.out.println("Login button clicked");
    System.out.println("Login panel visible: " + login.isVisible()); // ✅ here
         String username = txtUsername.getText().trim();
    String password = txtPassword.getText().trim();
    
     System.out.println("Trying to log in with: " + username + " / " + password);
     
    UserAccount ua = system.authenticateUser(username, password);

   if (ua != null) {
    System.out.println("Login successful. Role: " + ua.getRole().getClass().getSimpleName());

    JPanel rolePanel = ua.getRole().createWorkArea(workarea, ua, system);

    workarea.add("RolePanel", rolePanel);  // 🔄 Add to CardLayout with key
    ((CardLayout) workarea.getLayout()).show(workarea, "RolePanel");  // ✅ Show that card

} else {
    System.out.println("Login failed");
    JOptionPane.showMessageDialog(this, "Invalid credentials", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnLogicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogic;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblCinemaAndTheatreManagementSystem;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel login;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel workarea;
    // End of variables declaration//GEN-END:variables
}

