/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ConcessionPanel;

import Business.CartItem;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ConcessionOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FoodOrderRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ushakeshravyacopy
 */
public class ViewFoodRequestsPanel extends javax.swing.JPanel {
    
    private JPanel workarea;
private EcoSystem system;
private UserAccount user;
    /**
     * Creates new form ViewFoodRequestsPanel
     */
    public ViewFoodRequestsPanel(JPanel workarea, EcoSystem system, UserAccount user) {
        this.workarea = workarea;
    this.system = system;
    this.user = user;
        initComponents();
        populateTable();
    }

private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblFoodRequests.getModel();
    model.setRowCount(0);

    for (FoodOrderRequest fr : system.getFoodOrderRequests()) {
        String sender = fr.getSender().getusername();
        String items = fr.getCartItems().stream()
                         .map(item -> item.getFoodName() + " x" + item.getQuantity())
                         .reduce((a, b) -> a + ", " + b).orElse("No items");
        int total = 0;
        for (CartItem item : fr.getCartItems()) {
            total += item.getPrice();
        }

        model.addRow(new Object[]{sender, items, total, fr.getStatus()});
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblFoodRequests = new javax.swing.JTable();
        btnMarkasProcessed = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblFoodRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Items", "Total Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFoodRequests);

        btnMarkasProcessed.setText("Mark as Processed");
        btnMarkasProcessed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkasProcessedActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("View Food Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnMarkasProcessed))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnMarkasProcessed)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarkasProcessedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkasProcessedActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFoodRequests.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a request to mark as processed.");
        return;
    }

    String sender = tblFoodRequests.getValueAt(selectedRow, 0).toString();

    for (FoodOrderRequest fr : system.getFoodOrderRequests()) {
        if (fr.getSender() != null && fr.getSender().getusername().equals(sender)) {
            fr.setStatus("Processed");
            JOptionPane.showMessageDialog(this, "Marked as processed!");
            populateTable();
            return;
        }
    }

    JOptionPane.showMessageDialog(this, "Request not found.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnMarkasProcessedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMarkasProcessed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFoodRequests;
    // End of variables declaration//GEN-END:variables
}
