/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import static java.time.Clock.system;
import static java.time.InstantSource.system;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingConstants;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class AdminDashboardPanel extends ui.GradientPanel {
    
    private final JPanel workarea;
    private final EcoSystem system;


    /**
     * Creates new form AdminDashboardPanel
     */
   public AdminDashboardPanel(JPanel workarea, UserAccount account, EcoSystem system) {
     super(  // 👇 Gradient: Red → Black → Silver
            new Color[] {
                new Color(139, 0, 0),
                new Color(30, 30, 30),
                new Color(192, 192, 192)
            },
            new float[] { 0f, 0.5f, 1f }
        );
    this.workarea = workarea;
    this.system = system;
    initComponents();
    rebuildLayoutProperly();
    
}
   private void rebuildLayoutProperly() {
    this.removeAll();
    this.setLayout(new BorderLayout());
    this.setOpaque(false); // Keep gradient visible

    // ========== TOP BAR ==========
    JPanel topPanel = new JPanel(new BorderLayout());
    topPanel.setOpaque(false);
    topPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

    btnBack.setPreferredSize(new Dimension(80, 30));
    topPanel.add(btnBack, BorderLayout.WEST);

    jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
    jLabel1.setFont(new Font("SansSerif", Font.BOLD, 20));
    topPanel.add(jLabel1, BorderLayout.CENTER);

    this.add(topPanel, BorderLayout.NORTH);

    // ========== CENTER CONTENT ==========
    JPanel centerPanel = new JPanel();
    centerPanel.setOpaque(false);
    centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
    centerPanel.setBorder(BorderFactory.createEmptyBorder(40, 20, 40, 20));

    // Button Row (Manage + Add)
    JPanel btnRow = new JPanel();
    btnRow.setOpaque(false);
    btnRow.setLayout(new BoxLayout(btnRow, BoxLayout.X_AXIS));
    btnManageUserAccounts.setAlignmentX(Component.CENTER_ALIGNMENT);
    btnAddNewUserAccount.setAlignmentX(Component.CENTER_ALIGNMENT);
    btnRow.add(btnManageUserAccounts);
    btnRow.add(Box.createHorizontalStrut(20));
    btnRow.add(btnAddNewUserAccount);
    btnRow.setAlignmentX(Component.CENTER_ALIGNMENT);

    // Assemble center content
    centerPanel.add(Box.createVerticalGlue());
    centerPanel.add(btnRow);
    centerPanel.add(Box.createVerticalStrut(30));
    btnLogOut.setAlignmentX(Component.CENTER_ALIGNMENT);
    centerPanel.add(btnLogOut);
    centerPanel.add(Box.createVerticalGlue());

    this.add(centerPanel, BorderLayout.CENTER);

    // Refresh the panel
    this.revalidate();
    this.repaint();
}

   
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageUserAccounts = new javax.swing.JButton();
        btnAddNewUserAccount = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Dashboard");

        btnManageUserAccounts.setText("Manage User Accounts");
        btnManageUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountsActionPerformed(evt);
            }
        });

        btnAddNewUserAccount.setText("Add New User Account");
        btnAddNewUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserAccountActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btnLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnManageUserAccounts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnAddNewUserAccount)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageUserAccounts)
                    .addComponent(btnAddNewUserAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
    ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountsActionPerformed
        // TODO add your handling code here:
         ManageUserAccountPanel panel = new ManageUserAccountPanel(workarea, system);
    workarea.add("ManageUserAccountPanel", panel);
    ((CardLayout) workarea.getLayout()).show(workarea, "ManageUserAccountPanel");
        
    }//GEN-LAST:event_btnManageUserAccountsActionPerformed

    private void btnAddNewUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserAccountActionPerformed
        // TODO add your handling code here:
        AddNewUserPanel panel = new AddNewUserPanel(workarea, system);
    workarea.add("AddNewUserPanel", panel);
    ((CardLayout) workarea.getLayout()).show(workarea, "AddNewUserPanel");
    }//GEN-LAST:event_btnAddNewUserAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
    ((CardLayout) workarea.getLayout()).previous(workarea);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUserAccount;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
