/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminPanel;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class EditUserPanel extends ui.GradientPanel {

    private JPanel workarea;
    private EcoSystem system;
    private UserAccount user;
   

    /**
     * Creates new form EditUserPanel
     */
    public EditUserPanel(JPanel workarea, EcoSystem system, UserAccount user) {
        super(  // 👇 Gradient: Red → Black → Silver
            new Color[] {
                new Color(139, 0, 0),
                new Color(30, 30, 30),
                new Color(192, 192, 192)
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system = system;
        this.user = user;
        initComponents();
        
         // ⬇️ Replace models to store Organization/Role objects (not Strings)
    cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>());
    cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>());
        populateFields();
    }
    
   private void populateFields() {
    txtUsername.setText(user.getusername());
    txtPassword.setText(user.getPassword());

    // 🌟 Populate organizations as strings
    cmbOrganization.removeAllItems();
    cmbOrganization.addItem("Content Acquisition");
    cmbOrganization.addItem("Distribution Team");
    cmbOrganization.addItem("Operational Management");
    cmbOrganization.addItem("Box Office");
    cmbOrganization.addItem("Facility Staff");
    cmbOrganization.addItem("Oversight & Finance");

    // 🌟 Populate roles as strings
    cmbRole.removeAllItems();
    cmbRole.addItem("Producer");
    cmbRole.addItem("Distributor");
    cmbRole.addItem("Manager");
    cmbRole.addItem("Ticket Seller");
    cmbRole.addItem("Customer");
    cmbRole.addItem("Concession Staff");
    cmbRole.addItem("Technician");
    cmbRole.addItem("Accountant");

    // 🌟 Select current values (match strings)
    cmbOrganization.setSelectedItem(user.getOrganization());
    cmbRole.setSelectedItem(getRoleString(user.getRole()));
}

// Helper to match Role instance to string
private String getRoleString(Role role) {
    if (role instanceof Business.Role.ProducerRole) return "Producer";
    if (role instanceof Business.Role.DistributorRole) return "Distributor";
    if (role instanceof Business.Role.ManagerRole) return "Manager";
    if (role instanceof Business.Role.TicketSellerRole) return "Ticket Seller";
    if (role instanceof Business.Role.CustomerRole) return "Customer";
    if (role instanceof Business.Role.ConcessionStaffRole) return "Concession Staff";
    if (role instanceof Business.Role.TechnicianRole) return "Technician";
    if (role instanceof Business.Role.AccountantRole) return "Accountant";
    return "Unknown";
}

private Role getRoleFromString(String roleName) {
    switch (roleName) {
        case "Producer":
            return new Business.Role.ProducerRole();
        case "Distributor":
            return new Business.Role.DistributorRole();
        case "Manager":
            return new Business.Role.ManagerRole();
        case "Ticket Seller":
            return new Business.Role.TicketSellerRole();
        case "Customer":
            return new Business.Role.CustomerRole();
        case "Concession Staff":
            return new Business.Role.ConcessionStaffRole();
        case "Technician":
            return new Business.Role.TechnicianRole();
        case "Accountant":
            return new Business.Role.AccountantRole();
        default:
            return null;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblEditUserAccount = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox<>();
        cmbOrganization = new javax.swing.JComboBox<>();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEditUserAccount.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEditUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblEditUserAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditUserAccount.setText("Edit User Account");

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username :");

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password :");

        lblOrganization.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganization.setText("Organization :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role :");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditUserAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(100, 100, 100)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPassword)
                                    .addComponent(lblOrganization)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword)
                                    .addComponent(cmbRole, 0, 183, Short.MAX_VALUE)
                                    .addComponent(cmbOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblEditUserAccount)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    String newUsername = txtUsername.getText().trim();
    String newPassword = txtPassword.getText().trim();
    String newOrg = (String) cmbOrganization.getSelectedItem();
    String newRoleStr = (String) cmbRole.getSelectedItem();

    if (newUsername.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username and Password cannot be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Check for username conflict with other users
    for (UserAccount ua : system.getUserAccountDirectory().getUserList()) {
        if (ua != user && ua.getusername().equals(newUsername)) {
            JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different one.", "Conflict", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    // Update the user account with edited values
    user.setusername(newUsername);
    user.setPassword(newPassword);
    user.setOrganization(newOrg);
    user.setRole(getRoleFromString(newRoleStr));

    JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

    // Go back
    workarea.remove(this);
    ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Discard all changes and go back?", "Cancel Edit", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbOrganization;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEditUserAccount;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
