/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ushakeshravya
 */
public class ManageUserAccountPanel extends ui.GradientPanel {

    private final JPanel workarea;
    private final EcoSystem system;


    /**
     * Creates new form ManageUserAccountPanel
     */
    public ManageUserAccountPanel(JPanel workarea, EcoSystem system) {
super(  // 👇 Gradient: Red → Black → Silver
            new Color[] {
                new Color(139, 0, 0),
                new Color(30, 30, 30),
                new Color(192, 192, 192)
            },
            new float[] { 0f, 0.5f, 1f }
        );
    this.workarea = workarea;
    this.system = system;
    initComponents();
        populateTable();
    }
    
    private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblMngUserAccnts.getModel();
    model.setRowCount(0);

    for (UserAccount ua : system.getUserAccountDirectory().getUserList()) {
        Object[] row = new Object[3];
        row[0] = ua.getusername();
        row[1] = ua.getRole(); // Use correct getter
        row[2] = ua.getOrganization(); // Use correct getter
        model.addRow(row);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMngUserAccnts = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage User Accounts");

        tblMngUserAccnts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Role", "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMngUserAccnts);
        if (tblMngUserAccnts.getColumnModel().getColumnCount() > 0) {
            tblMngUserAccnts.getColumnModel().getColumn(0).setResizable(false);
            tblMngUserAccnts.getColumnModel().getColumn(1).setResizable(false);
            tblMngUserAccnts.getColumnModel().getColumn(2).setResizable(false);
        }

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBack)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnDelete)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
    ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMngUserAccnts.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, 
            "Please select a user to delete.", 
            "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Grab the username from the selected table row:
    String username = (String) tblMngUserAccnts.getValueAt(selectedRow, 0);

    // Find the matching UserAccount object:
    UserAccount toRemove = null;
    for (UserAccount ua : system.getUserAccountDirectory().getUserList()) {
        if (ua.getusername().equals(username)) {
            toRemove = ua;
            break;
        }
    }

    if (toRemove != null) {
        // Remove it via your helper (or directly from the list):
        system.getUserAccountDirectory().removeUserAccount(toRemove);

        JOptionPane.showMessageDialog(this, 
            "User \"" + username + "\" deleted.", 
            "Info", JOptionPane.INFORMATION_MESSAGE);

        // Refresh the table:
        populateTable();
    } else {
        JOptionPane.showMessageDialog(this, 
            "Error: could not find the selected user.", 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMngUserAccnts;
    // End of variables declaration//GEN-END:variables
}
