/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TicketSellerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.TicketingRequest;
import Business.WorkRequest.FinancialUpdateRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ushakeshravya
 */
public class TicketingRequestsPanel extends javax.swing.JPanel {
    private final JPanel workarea;
    private final EcoSystem system;
    private final UserAccount user;

    /**
     * Creates new form TicketingRequestsPanel
     */
    public TicketingRequestsPanel(JPanel workarea, EcoSystem system, UserAccount user) {
        this.workarea = workarea;
        this.system   = system;
        this.user     = user;
        initComponents();
        populateTable();
    }
    
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblTicketingRequests.getModel();
        model.setRowCount(0);
        List<TicketingRequest> list = system.getTicketingRequests();
        for (TicketingRequest r : list) {
            model.addRow(new Object[] {
                r.getMovieTitle(),
                r.getNumTickets(),
                r.getCustomerName(), 
                r.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTicketingRequests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicketingRequests = new javax.swing.JTable();
        btnIssueTickets = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTicketingRequests.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTicketingRequests.setText("Ticketing Requests");

        tblTicketingRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Show Name", "Seats ", "Customer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTicketingRequests);
        if (tblTicketingRequests.getColumnModel().getColumnCount() > 0) {
            tblTicketingRequests.getColumnModel().getColumn(0).setResizable(false);
            tblTicketingRequests.getColumnModel().getColumn(1).setResizable(false);
            tblTicketingRequests.getColumnModel().getColumn(2).setResizable(false);
            tblTicketingRequests.getColumnModel().getColumn(3).setResizable(false);
        }

        btnIssueTickets.setText("Issue Tickets");
        btnIssueTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueTicketsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack)
                        .addGap(85, 85, 85)
                        .addComponent(lblTicketingRequests))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnIssueTickets)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTicketingRequests))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBack)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnIssueTickets)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIssueTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueTicketsActionPerformed
        // TODO add your handling code here:
        int row = tblTicketingRequests.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a row first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TicketingRequest r = system.getTicketingRequests().get(row);
        if (!r.getStatus().equals("Pending")) {
            JOptionPane.showMessageDialog(this, "Already processed.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 1) mark this request “Issued”
        r.setStatus("Issued");

        // 2) create a financial update for the accountant
        //    (e.g. amount = seats * ticket price, here assume $10 each)
        double amount = r.getNumTickets() * 10.0;
        FinancialUpdateRequest finReq = new FinancialUpdateRequest(
            "Issued tickets for " + r.getMovieTitle() 
                + ", customer=" + r.getCustomerName(),
            amount
        );
        system.addFinancialRequest(finReq);

        JOptionPane.showMessageDialog(this, 
            "Tickets issued and Financial update created.", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE
        );
        populateTable();
    }//GEN-LAST:event_btnIssueTicketsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnIssueTickets;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTicketingRequests;
    private javax.swing.JTable tblTicketingRequests;
    // End of variables declaration//GEN-END:variables
}
