/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TicketSellerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.TicketBookingRequest;
import Business.WorkRequest.TicketingRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ushakeshravya
 */
public class TicketSellerDashboardPanel extends javax.swing.JPanel {
     private final JPanel workarea;
    private final EcoSystem system;
    private final UserAccount user;

    /**
     * Creates new form TicketSellerDashboardPanel
     */
    public TicketSellerDashboardPanel(JPanel workarea, UserAccount user, EcoSystem system) {
        this.workarea = workarea;
        this.system   = system;
        this.user     = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTicketingRequests = new javax.swing.JButton();
        btnBookingRequests = new javax.swing.JButton();
        lblTicketSellerDashboard = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        btnTicketingRequests.setText("Ticketing Requests");
        btnTicketingRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketingRequestsActionPerformed(evt);
            }
        });

        btnBookingRequests.setText("Booking Requests");
        btnBookingRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingRequestsActionPerformed(evt);
            }
        });

        lblTicketSellerDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTicketSellerDashboard.setText("TicketSeller Dashboard ");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(btnTicketingRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnBookingRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addGap(54, 54, 54)
                .addComponent(lblTicketSellerDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblTicketSellerDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBack)))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookingRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTicketingRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookingRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingRequestsActionPerformed
        // TODO add your handling code here:
        BookingRequestsPanel brPanel = new BookingRequestsPanel(workarea, system, user);
        workarea.add("BookingRequestsPanel", brPanel);
        CardLayout layout = (CardLayout) workarea.getLayout();
        layout.next(workarea);
    }//GEN-LAST:event_btnBookingRequestsActionPerformed

    private void btnTicketingRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketingRequestsActionPerformed
        // TODO add your handling code here:
        // 1) instantiate the TicketingRequestsPanel
        TicketingRequestsPanel trPanel = new TicketingRequestsPanel(workarea, system, user);
        // 2) add to card layout
        workarea.add("TicketingRequestsPanel", trPanel);
        // 3) flip to it
        CardLayout layout = (CardLayout) workarea.getLayout();
        layout.next(workarea);
        
    }//GEN-LAST:event_btnTicketingRequestsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookingRequests;
    private javax.swing.JButton btnTicketingRequests;
    private javax.swing.JLabel lblTicketSellerDashboard;
    // End of variables declaration//GEN-END:variables
}
