/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TechnicianPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.StaffAssignmentRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.GradientPanel;
/**
 *
 * @author ushakeshravya
 */
public class TechnicianDashboardPanel extends GradientPanel {
    private final JPanel workarea;
    private final EcoSystem system;
    private final UserAccount user;

    /**
     * Creates new form TechnicianDashboardPanel
     */
    public TechnicianDashboardPanel(JPanel workarea, EcoSystem system, UserAccount user) {
        super(
            new Color[] {
                new Color(64, 224, 208),    // Turquoise
                new Color(175, 238, 238),   // Pale Turquoise
                new Color(72, 209, 204)     // Medium Turquoise
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system   = system;
        this.user     = user;
        initComponents();
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblTechnicianDashboard.getModel();
        model.setRowCount(0);
        for (StaffAssignmentRequest r : system.getStaffAssignmentRequests()) {
            if ("Technician".equals(user.getRole().toString())
             && user.getUsername().equals(r.getAssignedStaff())
             && !"Completed".equals(r.getStatus())) {
                model.addRow(new Object[]{
                    r.getMovieTitle(),
                    r.getBudget(),
                    r.getStatus()
                });
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTechnicianDashboard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTechnicianDashboard = new javax.swing.JTable();
        btnComplete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTechnicianDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTechnicianDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTechnicianDashboard.setText("Technician Dashboard");

        tblTechnicianDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Title", "Budget", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTechnicianDashboard);
        if (tblTechnicianDashboard.getColumnModel().getColumnCount() > 0) {
            tblTechnicianDashboard.getColumnModel().getColumn(0).setResizable(false);
            tblTechnicianDashboard.getColumnModel().getColumn(1).setResizable(false);
            tblTechnicianDashboard.getColumnModel().getColumn(2).setResizable(false);
        }

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnComplete)
                        .addGap(231, 231, 231))))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack)
                .addGap(82, 82, 82)
                .addComponent(lblTechnicianDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTechnicianDashboard)
                    .addComponent(btnBack))
                .addGap(145, 145, 145)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnComplete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        int row = tblTechnicianDashboard.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a row first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String title = (String)tblTechnicianDashboard.getValueAt(row, 0);
        for (StaffAssignmentRequest r : system.getStaffAssignmentRequests()) {
            if (r.getMovieTitle().equals(title)
             && r.getAssignedStaff().equals(user.getUsername())) {
                r.setStatus("Completed");
                break;
            }
        }
        JOptionPane.showMessageDialog(this, "Marked completed.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComplete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTechnicianDashboard;
    private javax.swing.JTable tblTechnicianDashboard;
    // End of variables declaration//GEN-END:variables
}
