/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.CartItem;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ConcessionOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FoodOrderRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.time.Clock.system;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.Timer;
import ui.GradientPanel;
/**
 *
 * @author ushakeshravya
 */
public class CartPanel extends GradientPanel {
    private EcoSystem system;
    private JPanel workarea;
    private UserAccount user;
private List<CartItem> cart;
private javax.swing.table.DefaultTableModel model;




    /**
     * Creates new form CartPanel
     */
    public CartPanel(JPanel workarea, EcoSystem system, UserAccount user) {
        super(
            new Color[] {
                new Color(221, 160, 221),   // Soft Lavender
                new Color(230, 230, 250),   // Lavender
                new Color(216, 191, 216)    // Thistle
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
    this.system = system; 
    this.user = user;
    this.cart = user.getCart();
        initComponents();
        

    updateTotal();
    


        populateTable();
    }
    
    private void populateTable() {
    model = (javax.swing.table.DefaultTableModel) tblCartItems.getModel();
    model.setRowCount(0);
    for (CartItem item : cart) {
        model.addRow(new Object[]{item.getFoodName(), item.getQuantity(), item.getPrice()});
    }
    System.out.println("CartPanel opened. Cart size: " + cart.size());

        
}

private void updateTotal() {
    int total = 0;
    for (CartItem item : cart) {
        total += item.getPrice();
    }
    txtTotal.setText(String.valueOf(total));
}

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartItems = new javax.swing.JTable();
        btnEditQuantity = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCart = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();

        tblCartItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Item", "Qty ", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCartItems);

        btnEditQuantity.setText("Edit Quantity");
        btnEditQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuantityActionPerformed(evt);
            }
        });

        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        lblTotal.setText("Total : ");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCart.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCart.setText("🛒 Your Cart ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnEditQuantity)
                        .addGap(33, 33, 33)
                        .addComponent(btnRemoveItem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(lblTotal)
                            .addGap(18, 18, 18)
                            .addComponent(txtTotal))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(btnPlaceOrder))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNotification)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(5, 5, 5)
                .addComponent(lblCart)
                .addGap(4, 4, 4)
                .addComponent(lblNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditQuantity)
                    .addComponent(btnRemoveItem))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnPlaceOrder)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuantityActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCartItems.getSelectedRow();
        if (selectedRow >= 0) {
            CartItem selectedItem = cart.get(selectedRow);
            String newQtyStr = javax.swing.JOptionPane.showInputDialog(this,
                "Enter new quantity for " + selectedItem.getFoodName() + ":",
                selectedItem.getQuantity());
            if (newQtyStr != null) {
                try {
                    int newQty = Integer.parseInt(newQtyStr);
                    if (newQty <= 0) throw new NumberFormatException();

                    // Recalculate price
                    int pricePerUnit = (int) (selectedItem.getPrice() / selectedItem.getQuantity());
                    selectedItem.setQuantity(newQty);
                    selectedItem.setPrice(pricePerUnit * newQty);

                    populateTable();
                    updateTotal();
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid quantity entered.");
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item to edit.");
        }
    }//GEN-LAST:event_btnEditQuantityActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCartItems.getSelectedRow();
        if (selectedRow >= 0) {
            cart.remove(selectedRow);
            populateTable();
            updateTotal();
            javax.swing.JOptionPane.showMessageDialog(this, "Item removed from cart.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an item to remove.");
        }
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        if (cart.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty.");
            return;
        }

        // ✅ Create food order request BEFORE clearing the cart
        FoodOrderRequest request = new FoodOrderRequest();
        request.setSender(user);
        request.setStatus("Placed");
        request.setCartItems(new ArrayList<>(cart)); // ✅ make a copy
        request.setRequestDate(new java.util.Date());

        // ✅ Add to global food list
        system.addFoodOrderRequest(request);

        // ✅ Clear the cart after placing order
cart.clear();
        javax.swing.JOptionPane.showMessageDialog(this, "Order placed successfully!");

        populateTable();
        updateTotal();
        



    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditQuantity;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCart;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCartItems;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
