/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FoodOrderRequest;
import Business.WorkRequest.TicketBookingRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class CustomerDashboardPanel extends GradientPanel {
    private final JPanel workarea;
    private final EcoSystem system;
    private final UserAccount user;


    /**
     * Creates new form CustomerDashboardPanel
     */
    public CustomerDashboardPanel(JPanel workarea, EcoSystem system, UserAccount user) {
         super(
            new Color[] {
                new Color(221, 160, 221),   // Soft Lavender
                new Color(230, 230, 250),   // Lavender
                new Color(216, 191, 216)    // Thistle
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system   = system;
       this.user     = user;
        initComponents();
        populateTable();
        

   

    }
    
    public void populateTable() {
    DefaultTableModel m = (DefaultTableModel) tblBookingReq.getModel();
    m.setRowCount(0);
    for (TicketBookingRequest r : system.getTicketBookingRequests()) {
        if (r.getCustomer().equals(user.getusername())) {
            m.addRow(new Object[]{
                r.getShowName(),
                r.getSeats(),
                r.getStatus()
            });
        }
    }
}

    private void checkForProcessedFoodOrders() {
    boolean shouldNotify = false;

    for (FoodOrderRequest r : system.getFoodOrderRequests()) {
        if (r.getSender().equals(user)
            && "Processed".equalsIgnoreCase(r.getStatus())
            && r.getProcessedDate() != null
            && (user.getLastSeenFoodNotification() == null
                || r.getProcessedDate().after(user.getLastSeenFoodNotification()))) {

            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this,
                "🍿 Your food order has been processed!",
                "Order Ready", JOptionPane.INFORMATION_MESSAGE);

            shouldNotify = true;
            break;
        }
    }

    if (shouldNotify) {
        user.setLastSeenFoodNotification(new Date());
    }
}

  @Override
public void addNotify() {
    super.addNotify();

    javax.swing.SwingUtilities.invokeLater(() -> {
        checkForProcessedFoodOrders();
    });
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerDashboard = new javax.swing.JLabel();
        lblPreviousBookingRequests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookingReq = new javax.swing.JTable();
        btnBookTicket = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblEmailId = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        btnOrderFood = new javax.swing.JButton();

        lblCustomerDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCustomerDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerDashboard.setText("Customer Dashboard");

        lblPreviousBookingRequests.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPreviousBookingRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreviousBookingRequests.setText("Previous Booking Requests:");

        tblBookingReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Show Name", "Seats", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBookingReq);
        if (tblBookingReq.getColumnModel().getColumnCount() > 0) {
            tblBookingReq.getColumnModel().getColumn(0).setResizable(false);
            tblBookingReq.getColumnModel().getColumn(1).setResizable(false);
            tblBookingReq.getColumnModel().getColumn(2).setResizable(false);
        }

        btnBookTicket.setText("Book Ticket");
        btnBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicketActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEmailId.setText("Email Id :");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        btnOrderFood.setText("Order Food");
        btnOrderFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderFoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblEmailId)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(lblCustomerDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(lblPreviousBookingRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrderFood, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(20, 20, 20)
                .addComponent(lblCustomerDashboard)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailId)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblPreviousBookingRequests)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderFood, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
        // TODO add your handling code here:
        String email = txtEmailId.getText().trim();
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter your email before booking.",
            "Missing Email",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // ✅ Updated Regex: Allow gmail, yahoo, outlook, northeastern
    String emailRegex = "^[a-zA-Z0-9._%+-]+@(gmail\\.com|yahoo\\.com|outlook\\.com|northeastern\\.edu)$";
    if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(this,
            "Invalid email format. Please use a valid email like abc@gmail.com, abc@yahoo.com, abc@outlook.com or abc@northeastern.edu",
            "Invalid Email",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

         SelectShowPanel panel =
        new SelectShowPanel(workarea, system, user, email);
    workarea.add("TicketBooking", panel);
    ((CardLayout)workarea.getLayout()).next(workarea);
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void btnOrderFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderFoodActionPerformed
        // TODO add your handling code here:
        CustomerFoodOrderPanel panel = new CustomerFoodOrderPanel(workarea, system, user);
        workarea.add("OrderFood", panel);
        ((CardLayout)workarea.getLayout()).next(workarea);
    }//GEN-LAST:event_btnOrderFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton btnOrderFood;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerDashboard;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblPreviousBookingRequests;
    private javax.swing.JTable tblBookingReq;
    private javax.swing.JTextField txtEmailId;
    // End of variables declaration//GEN-END:variables
}
