/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.TicketBookingRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class CustomerDashboardPanel extends GradientPanel {
    private final JPanel workarea;
    private final EcoSystem system;
    private final UserAccount user;


    /**
     * Creates new form CustomerDashboardPanel
     */
    public CustomerDashboardPanel(JPanel workarea, EcoSystem system, UserAccount user) {
         super(
            new Color[] {
                new Color(221, 160, 221),   // Soft Lavender
                new Color(230, 230, 250),   // Lavender
                new Color(216, 191, 216)    // Thistle
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system   = system;
       this.user     = user;
        initComponents();
        populateTable();
    }
    
    public void populateTable() {
    DefaultTableModel m = (DefaultTableModel) tblBookingReq.getModel();
    m.setRowCount(0);
    for (TicketBookingRequest r : system.getTicketBookingRequests()) {
        if (r.getCustomer().equals(user.getUsername())) {
            m.addRow(new Object[]{
                r.getShowName(),
                r.getSeats(),
                r.getStatus()
            });
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerDashboard = new javax.swing.JLabel();
        lblPreviousBookingRequests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookingReq = new javax.swing.JTable();
        btnBookTicket = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblEmailId = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();

        lblCustomerDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblCustomerDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerDashboard.setText("Customer Dashboard");

        lblPreviousBookingRequests.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPreviousBookingRequests.setText("Previous Booking Requests:");

        tblBookingReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Show Name", "Seats", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBookingReq);
        if (tblBookingReq.getColumnModel().getColumnCount() > 0) {
            tblBookingReq.getColumnModel().getColumn(0).setResizable(false);
            tblBookingReq.getColumnModel().getColumn(1).setResizable(false);
            tblBookingReq.getColumnModel().getColumn(2).setResizable(false);
        }

        btnBookTicket.setText("Book Ticket");
        btnBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicketActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEmailId.setText("Email Id :");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPreviousBookingRequests)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnBack)
                        .addGap(75, 75, 75)
                        .addComponent(lblCustomerDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblEmailId)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnBookTicket)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblCustomerDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailId)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblPreviousBookingRequests)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnBookTicket)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
        // TODO add your handling code here:
        String email = txtEmailId.getText().trim();
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter your email before booking.",
            "Missing Email",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    // ...then hand off to TicketBookingRequestPanel, including email:
    String customerEmail = txtEmailId.getText().trim();
         TicketBookingRequestPanel panel =
        new TicketBookingRequestPanel(workarea, system, user, customerEmail);
    workarea.add("TicketBooking", panel);
    ((CardLayout)workarea.getLayout()).next(workarea);
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerDashboard;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblPreviousBookingRequests;
    private javax.swing.JTable tblBookingReq;
    private javax.swing.JTextField txtEmailId;
    // End of variables declaration//GEN-END:variables
}
