/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.CartItem;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.CartItem;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.SwingConstants;

/**
 *
 * @author ushakeshravya
 */
public class CustomerFoodOrderPanel extends javax.swing.JPanel {

    private JPanel workarea;
    private EcoSystem system;
    private UserAccount user;
    private List<CartItem> cart = new ArrayList<>();
    private String selectedItem = "";
    private int quantity = 1;
    private String foodName;

    /**
     * Creates new form CustomerFoodOrderPanel
     */
    public CustomerFoodOrderPanel(JPanel workarea, EcoSystem system, UserAccount user) {
        this.workarea = workarea;
        this.system = system;
        this.user = user;
        initComponents();
        txtPrice.setText("0.0");
       

    }

    private void updatePrice() {
        int pricePerUnit = switch (selectedItem) {
            case "Popcorn" ->
                5;
            case "Coke" ->
                3;
            case "Chocolate" ->
                4;
            default ->
                0;
        };
        txtPrice.setText(String.valueOf(quantity * pricePerUnit));
    }

    private int getPriceForItem(String foodName) {
        switch (foodName.toLowerCase()) {
            case "popcorn":
                return 120;
            case "coke":
                return 80;
            case "nachos":
                return 150;
            default:
                return 100;  // default price
        }
    }

  
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQty = new javax.swing.JLabel();
        btnAddtoCart = new javax.swing.JButton();
        btnViewCart = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        lblFoodOrder = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnPopcorn = new javax.swing.JButton();
        btnCoke = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();

        lblQty.setText("Qty : ");

        btnAddtoCart.setText("Add to Cart");
        btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCartActionPerformed(evt);
            }
        });

        btnViewCart.setText("View Cart 🛒");
        btnViewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCartActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        lblFoodOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblFoodOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoodOrder.setText("Order Food");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory.setText("Category :");

        lblPrice.setText("Price :");

        btnPopcorn.setText("🍟 Popcorn");
        btnPopcorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopcornActionPerformed(evt);
            }
        });

        btnCoke.setText("🥤 Coke");
        btnCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCokeActionPerformed(evt);
            }
        });

        btnChocolate.setText("🍫 Chocolate");
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoodOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddtoCart)
                        .addGap(178, 178, 178)
                        .addComponent(btnViewCart)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblQty)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPrice))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPopcorn)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnCoke, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnChocolate)))))
                        .addGap(39, 39, 39)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFoodOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblCategory)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoke, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPopcorn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtoCart)
                    .addComponent(btnViewCart))
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
        // TODO add your handling code here:
        // Ensure a food item is selected
        if (selectedItem == null || selectedItem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a food item.");
            return;
        }

        // Ensure quantity is valid
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
            return;
        }

        // Calculate price and create item
        int pricePerItem = getPriceForItem(selectedItem);
        int totalPrice = pricePerItem * quantity;

        CartItem item = new CartItem(selectedItem, quantity, totalPrice);

        // Add to user's cart
        user.getCart().add(item);

        JOptionPane.showMessageDialog(this, "Item added to cart: " + selectedItem);
        System.out.println("Cart size now: " + user.getCart().size());
    }//GEN-LAST:event_btnAddtoCartActionPerformed

    private void btnViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCartActionPerformed
        // TODO add your handling code here:
        CartPanel cartPanel = new CartPanel(workarea, system, user);
workarea.add("CartPanel", cartPanel);
CardLayout layout = (CardLayout) workarea.getLayout();
layout.show(workarea, "CartPanel");  // ✅ explicitly show

    }//GEN-LAST:event_btnViewCartActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPopcornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopcornActionPerformed
        // TODO add your handling code here:
        selectedItem = "Popcorn";
        quantity = 1;
        txtPrice.setText(String.valueOf(quantity * 5)); // assuming 5 per popcorn
    }//GEN-LAST:event_btnPopcornActionPerformed

    private void btnCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCokeActionPerformed
        // TODO add your handling code here:
        selectedItem = "Coke";
        quantity = 1;
        txtPrice.setText(String.valueOf(quantity * 3)); // 3 per coke
    }//GEN-LAST:event_btnCokeActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        // TODO add your handling code here:
        selectedItem = "Chocolate";
        quantity = 1;
        txtPrice.setText(String.valueOf(quantity * 4)); // 4 per chocolate
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!selectedItem.isEmpty()) {
            quantity++;
            updatePrice();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        if (!selectedItem.isEmpty() && quantity > 1) {
            quantity--;
            updatePrice();
        }
    }//GEN-LAST:event_btnMinusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnCoke;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPopcorn;
    private javax.swing.JButton btnViewCart;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblFoodOrder;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
