/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import static java.time.Clock.system;
import Business.WorkRequest.TicketBookingRequest;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ushakeshravya
 */
public class SeatSelectionPanel extends javax.swing.JPanel {
     private final JPanel workarea;
     private final EcoSystem system;
private final UserAccount user;
private final String showName;
private final String email;


    /**
     * Creates new form SeatSelectionPanel
     */
    public SeatSelectionPanel(JPanel workarea, EcoSystem system, UserAccount user, String showName, String email) {
        this.workarea = workarea;
        this.system = system;
        this.user = user;
        this.showName = showName;
        this.email = email;
        initComponents();
        loadSeats();
    }
    
        public void loadSeats() {
    seatGridPanel.removeAll();  // Clear if already populated

    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 10; j++) {
            JButton seatBtn = new JButton((char)('A' + i) + String.valueOf(j + 1));
            seatBtn.setBackground(Color.GREEN);
            seatBtn.setOpaque(true);
            seatBtn.setBorderPainted(false);

            // Optional: Add click listener to toggle color
            seatBtn.addActionListener(e -> {
                if (seatBtn.getBackground() == Color.GREEN) {
                    seatBtn.setBackground(Color.YELLOW);  // selected
                } else if (seatBtn.getBackground() == Color.YELLOW) {
                    seatBtn.setBackground(Color.GREEN);   // unselected
                }
            });

            seatGridPanel.add(seatBtn);
        }
    }

    seatGridPanel.revalidate();
    seatGridPanel.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConfirmBooking = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        seatGridPanel = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Select your Seats");

        btnConfirmBooking.setText("Confirm Booking");
        btnConfirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmBookingActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        seatGridPanel.setLayout(new java.awt.GridLayout(5, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnConfirmBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(142, 142, 142))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(319, 319, 319)
                    .addComponent(seatGridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmBooking)
                    .addComponent(btnBack))
                .addGap(80, 80, 80))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(291, 291, 291)
                    .addComponent(seatGridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
            // TODO add your handling code here:
        List<String> selectedSeats = new ArrayList<>();

    for (Component comp : seatGridPanel.getComponents()) {
        if (comp instanceof JButton btn && btn.getBackground().equals(Color.YELLOW)) {
            selectedSeats.add(btn.getText());
        }
    }

    if (selectedSeats.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select at least one seat.");
        return;
    }

    TicketBookingRequest req = new TicketBookingRequest(
        showName,
        String.join(", ", selectedSeats),
        user.getUsername(),
        email
    );

    system.getTicketBookingRequests().add(req);
    JOptionPane.showMessageDialog(this, "Booking confirmed!");

    workarea.remove(this);
    ((CardLayout) workarea.getLayout()).previous(workarea);

    for (Component c : workarea.getComponents()) {
        if (c instanceof CustomerDashboardPanel) {
            ((CustomerDashboardPanel) c).populateTable();
        }
    }
    }//GEN-LAST:event_btnConfirmBookingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel seatGridPanel;
    // End of variables declaration//GEN-END:variables
}
