/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.TicketBookingRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.GradientPanel;


/**
 *
 * @author ushakeshravya
 */
public class SelectShowPanel extends GradientPanel {
    
    private final UserAccount user;
    private final JPanel workarea;
     private final EcoSystem system;
     private final String      customerEmail;  // ← new

    /**
     * Creates new form TicketBookingRequestPanel
     */
    public SelectShowPanel(JPanel workarea, EcoSystem system, UserAccount user, String customerEmail) {
        super(
            new Color[] {
                new Color(221, 160, 221),   // Soft Lavender
                new Color(230, 230, 250),   // Lavender
                new Color(216, 191, 216)    // Thistle
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
    this.system   = system;
    this.user     = user;
    this.customerEmail = customerEmail;     // store it
        initComponents();
         loadShows();
    
    }
    
    private void loadShows() {
    cmbShow.removeAllItems();
    // e.g. pull from system or hardcode for now:
    cmbShow.addItem("Avengers - 7:00 PM");
    cmbShow.addItem("Inception - 9:30 PM");
    // …etc
}

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectShow = new javax.swing.JLabel();
        lblShow = new javax.swing.JLabel();
        cmbShow = new javax.swing.JComboBox<>();
        btnContinuetoSeatSelection = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblSelectShow.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSelectShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectShow.setText("Select Show");

        lblShow.setText("Show :");

        cmbShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShowActionPerformed(evt);
            }
        });

        btnContinuetoSeatSelection.setText("Continue to Seat Selection");
        btnContinuetoSeatSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuetoSeatSelectionActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSelectShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(btnBack))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(lblShow)
                            .addGap(48, 48, 48)
                            .addComponent(cmbShow, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnContinuetoSeatSelection)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(27, 27, 27)
                .addComponent(lblSelectShow)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShow)
                    .addComponent(cmbShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addComponent(btnContinuetoSeatSelection)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuetoSeatSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuetoSeatSelectionActionPerformed
        // TODO add your handling code here:
       String showStr = (String) cmbShow.getSelectedItem();
if (showStr == null) {
    JOptionPane.showMessageDialog(this, "Please select a show", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
        // Navigate to seat selection screen
    SeatSelectionPanel seatPanel = new SeatSelectionPanel(workarea, system, user, showStr, customerEmail);
    workarea.add("SeatSelectionPanel", seatPanel);
    ((CardLayout) workarea.getLayout()).next(workarea);

    }//GEN-LAST:event_btnContinuetoSeatSelectionActionPerformed

    private void cmbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbShowActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinuetoSeatSelection;
    private javax.swing.JComboBox<String> cmbShow;
    private javax.swing.JLabel lblSelectShow;
    private javax.swing.JLabel lblShow;
    // End of variables declaration//GEN-END:variables
}
