/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CustomerPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.TicketBookingRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class TicketBookingRequestPanel extends GradientPanel {
    
    private final UserAccount user;
    private final JPanel workarea;
     private final EcoSystem system;
     private final String      customerEmail;  // ← new

    /**
     * Creates new form TicketBookingRequestPanel
     */
    public TicketBookingRequestPanel(JPanel workarea, EcoSystem system, UserAccount user, String customerEmail) {
        super(
            new Color[] {
                new Color(221, 160, 221),   // Soft Lavender
                new Color(230, 230, 250),   // Lavender
                new Color(216, 191, 216)    // Thistle
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
    this.system   = system;
    this.user     = user;
    this.customerEmail = customerEmail;     // store it
        initComponents();
         loadShows();
    loadSeats();
    }
    
    private void loadShows() {
    cmbShow.removeAllItems();
    // e.g. pull from system or hardcode for now:
    cmbShow.addItem("Avengers - 7:00 PM");
    cmbShow.addItem("Inception - 9:30 PM");
    // …etc
}
private void loadSeats() {
    cmbSeats.removeAllItems();
    for(int i=1;i<=10;i++) cmbSeats.addItem(String.valueOf(i));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewTicketBooking = new javax.swing.JLabel();
        lblShow = new javax.swing.JLabel();
        cmbShow = new javax.swing.JComboBox<>();
        lblSeats = new javax.swing.JLabel();
        cmbSeats = new javax.swing.JComboBox<>();
        btnSubmitBooking = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblNewTicketBooking.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNewTicketBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewTicketBooking.setText("New Ticket Booking   ");

        lblShow.setText("Show :");

        cmbShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShowActionPerformed(evt);
            }
        });

        lblSeats.setText("Seats :");

        cmbSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeatsActionPerformed(evt);
            }
        });

        btnSubmitBooking.setText("Submit Booking");
        btnSubmitBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitBookingActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShow)
                    .addComponent(lblSeats))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmitBooking)
                    .addComponent(cmbSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lblNewTicketBooking)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblNewTicketBooking))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShow)
                    .addComponent(cmbShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(cmbSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(btnSubmitBooking)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitBookingActionPerformed
        // TODO add your handling code here:
         String show = (String)cmbShow.getSelectedItem();
    int seats = Integer.parseInt((String)cmbSeats.getSelectedItem());
    if(show==null || seats<=0) {
       JOptionPane.showMessageDialog(this,"Select show & seats","Error",JOptionPane.ERROR_MESSAGE);
       return;
    }
    TicketBookingRequest req = new TicketBookingRequest(show, seats, user.getUsername(), customerEmail);
    system.addTicketBookingRequest(req);
    JOptionPane.showMessageDialog(this,"Booking submitted","Success",JOptionPane.INFORMATION_MESSAGE);

    // go back and refresh
    workarea.remove(this);
    CardLayout layout = (CardLayout)workarea.getLayout();
    layout.previous(workarea);
    Component[] comps = workarea.getComponents();
    // find dashboard:
    Component last = comps[comps.length-1];
    if(last instanceof CustomerDashboardPanel) {
      ((CustomerDashboardPanel)last).populateTable();
    }
    }//GEN-LAST:event_btnSubmitBookingActionPerformed

    private void cmbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbShowActionPerformed

    private void cmbSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSeatsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitBooking;
    private javax.swing.JComboBox<String> cmbSeats;
    private javax.swing.JComboBox<String> cmbShow;
    private javax.swing.JLabel lblNewTicketBooking;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblShow;
    // End of variables declaration//GEN-END:variables
}
