/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import javax.swing.*;
import java.awt.*;
import java.awt.geom.Point2D;

/**
 *
 * @author ushakeshravya
 */
public class GradientPanel extends javax.swing.JPanel {
    private Color[] colors;
    private float[] fractions;    /**
     * Creates new form GradientPanel
     */
     public GradientPanel(Color[] colors, float[] fractions) {
        this.colors = colors;
        this.fractions = fractions;
        setOpaque(false);
    }

  @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (colors != null && colors.length >= 2) {
            Graphics2D g2d = (Graphics2D) g.create();
            int width = getWidth();
            int height = getHeight();
            LinearGradientPaint paint = new LinearGradientPaint(
                0, 0, width, height, fractions, colors
            );
            g2d.setPaint(paint);
            g2d.fillRect(0, 0, width, height);
            g2d.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
