/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DistributorPanel;

import Business.EcoSystem;
import Business.WorkRequest.DistributionAssignmentRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkRequest.MovieAcquisitionRequest;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ushakeshravya
 */
public class AcquisitionRequestsPanel extends javax.swing.JPanel {
     private final JPanel workarea;
     private final EcoSystem system;
    /**
     * Creates new form AcquisitionRequestsPanel
     */
    public AcquisitionRequestsPanel(JPanel workarea, EcoSystem system) {
        this.workarea = workarea;
        this.system   = system;
        initComponents();
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblAcqRequests.getModel();
        model.setRowCount(0);
        for (MovieAcquisitionRequest r : system.getMovieRequests()) {
            model.addRow(new Object[]{ r.getMovieTitle(), r.getBudget(), r.getStatus() });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcqRequests = new javax.swing.JTable();
        lblAcquisitionRequests = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblAcqRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Title", "Budget", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAcqRequests);
        if (tblAcqRequests.getColumnModel().getColumnCount() > 0) {
            tblAcqRequests.getColumnModel().getColumn(0).setResizable(false);
            tblAcqRequests.getColumnModel().getColumn(1).setResizable(false);
            tblAcqRequests.getColumnModel().getColumn(2).setResizable(false);
        }

        lblAcquisitionRequests.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAcquisitionRequests.setText("Acquisition Requests");

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack)
                        .addGap(57, 57, 57)
                        .addComponent(lblAcquisitionRequests))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnAccept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReject)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblAcquisitionRequests))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBack)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
         int row = tblAcqRequests.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Select a row first.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 1) Mark the acquisition request accepted
    MovieAcquisitionRequest r = system.getMovieRequests().get(row);
    r.setStatus("Accepted");

    // 2) Create & register a DistributionAssignmentRequest
    DistributionAssignmentRequest dar =
        new DistributionAssignmentRequest(r.getMovieTitle(), r.getBudget());
    system.addDistributionAssignment(dar);

    // 3) Popup confirmation
    JOptionPane.showMessageDialog(
        this,
        "Acquisition request accepted!",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
    );

    // 4) Refresh YOUR own table
    populateTable();

    // 5) (optional) if you want to immediately jump to the assignments panel, you can do:
    /*
    DistributionAssignmentsPanel dap = new DistributionAssignmentsPanel(workarea, system);
    workarea.add("DistributionAssignments", dap);
    ((CardLayout)workarea.getLayout()).show(workarea, "DistributionAssignments");
    */
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tblAcqRequests.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a row first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        MovieAcquisitionRequest r = system.getMovieRequests().get(row);
        r.setStatus("Rejected");
        populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcquisitionRequests;
    private javax.swing.JTable tblAcqRequests;
    // End of variables declaration//GEN-END:variables
}
