/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DistributorPanel;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class DistributorDashboardPanel extends GradientPanel {
    
     private final JPanel workarea;
    private final EcoSystem system;

    /**
     * Creates new form DistributorDashboardPanel
     */
    public DistributorDashboardPanel(JPanel workarea, UserAccount ua, EcoSystem system) {
        super(
            new Color[] {
                new Color(192, 192, 192),   // Silver
                new Color(255, 215, 0),     // Light Gold
                new Color(218, 165, 32)     // Rich Gold
            },
            new float[] { 0f, 0.5f, 1f }
        );

        this.workarea = workarea;
        this.system   = system;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAcquisitionRequest = new javax.swing.JButton();
        btnDistributionAssignments = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Distributor Dashboard");

        btnAcquisitionRequest.setText("Acquisition Request ");
        btnAcquisitionRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcquisitionRequestActionPerformed(evt);
            }
        });

        btnDistributionAssignments.setText("Distribution Assignments");
        btnDistributionAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributionAssignmentsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAcquisitionRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDistributionAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)))
                .addGap(58, 58, 58)
                .addComponent(btnAcquisitionRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDistributionAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcquisitionRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcquisitionRequestActionPerformed
        // TODO add your handling code here:
        AcquisitionRequestsPanel panel = new AcquisitionRequestsPanel(workarea, system);
        workarea.add("AcqReqPanel", panel);
        ((CardLayout)workarea.getLayout()).next(workarea);
    }//GEN-LAST:event_btnAcquisitionRequestActionPerformed

    private void btnDistributionAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributionAssignmentsActionPerformed
        // TODO add your handling code here:
         DistributionAssignmentsPanel dap = new DistributionAssignmentsPanel(workarea, system);
    workarea.add("DistributionAssignments", dap);
    ((CardLayout)workarea.getLayout()).show(workarea, "DistributionAssignments");
    }//GEN-LAST:event_btnDistributionAssignmentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout) workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcquisitionRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDistributionAssignments;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
