/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountantPanel;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FinancialUpdateRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.GradientPanel;

/**
 *
 * @author ushakeshravya
 */
public class AccountantDashboardPanel extends GradientPanel {
     private final JPanel workarea;
    private final EcoSystem system;
    /**
     * Creates new form AccountantDashboardPanel
     */
    public AccountantDashboardPanel(JPanel workarea, UserAccount ua, EcoSystem system) {
        super(
            new Color[] {
                new Color(173, 216, 230),  // Light Sky Blue
                new Color(245, 245, 245),  // Powder White
                new Color(152, 251, 152)   // Mint Green
            },
            new float[] { 0f, 0.5f, 1f }
        );
        this.workarea = workarea;
        this.system   = system;
        initComponents();
        populateTable();

    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblFinancial.getModel();
        model.setRowCount(0);

        List<FinancialUpdateRequest> list = system.getFinancialRequests();
        for (FinancialUpdateRequest r : list) {
            model.addRow(new Object[]{
                r.getDescription(),
                String.format("%.2f", r.getAmount()),
                r.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccountantDashboard = new javax.swing.JLabel();
        lblFinancialUpdateRequests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFinancial = new javax.swing.JTable();
        btnRecordPayment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblAccountantDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAccountantDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccountantDashboard.setText("Accountant Dashboard  ");

        lblFinancialUpdateRequests.setText("Financial Update Requests  ");

        tblFinancial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Show", "Amount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFinancial);
        if (tblFinancial.getColumnModel().getColumnCount() > 0) {
            tblFinancial.getColumnModel().getColumn(0).setResizable(false);
            tblFinancial.getColumnModel().getColumn(1).setResizable(false);
            tblFinancial.getColumnModel().getColumn(2).setResizable(false);
        }

        btnRecordPayment.setText("Record Payment");
        btnRecordPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordPaymentActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBack)
                        .addGap(64, 64, 64)
                        .addComponent(lblAccountantDashboard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblFinancialUpdateRequests))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnRecordPayment)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountantDashboard)
                    .addComponent(btnBack))
                .addGap(36, 36, 36)
                .addComponent(lblFinancialUpdateRequests)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnRecordPayment)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordPaymentActionPerformed
        // TODO add your handling code here:
         int row = tblFinancial.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a row first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        FinancialUpdateRequest r = system.getFinancialRequests().get(row);
        if (r.getStatus().equals("Paid")) {
            JOptionPane.showMessageDialog(this, "Already marked as Paid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        r.setStatus("Paid");
        JOptionPane.showMessageDialog(this, "Marked as Paid.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
    }//GEN-LAST:event_btnRecordPaymentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workarea.remove(this);
        ((CardLayout)workarea.getLayout()).previous(workarea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRecordPayment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountantDashboard;
    private javax.swing.JLabel lblFinancialUpdateRequests;
    private javax.swing.JTable tblFinancial;
    // End of variables declaration//GEN-END:variables
}
